name: Initial

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'initial')
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  call-workflow-passing-data:
    uses: ./.github/workflows/secondary.yaml
    with:
      input1: $GITHUB_HEAD_REF
