name: Secondary

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      input1:
        description: Branch to test
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment: accounts
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Pass secret as JSON
        env:
          SECRET_JSON: ${{ secrets.ACCOUNT_DETAILS }}
        run: |
          echo "$SECRET_JSON" > account.json

      - name: Run a one-line script
        run: echo Hello, world from secondary ${{inputs.input1}}

      - name: Run node
        run: node ./test.js
