name: Secondary

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      input1:
        description: Branch to test
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world from secondary ${{inputs.input1}}
