name: Secondary

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      input1:
        description: Branch to test
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment: accounts
    steps:
      - name: Pass secret as JSON
        env:
          SECRET_JSON: ${{ secrets.ACCOUNT_DETAILS }}
        run: |
          echo "$SECRET_JSON" > secret.json
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Run a one-line script
        run: jq .username secret.json
      - name: Run a one-line script
        run: echo Hello, world from secondary ${{inputs.input1}}
